# Generated by Django 5.1.3 on 2024-11-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_students_superadmin_teachers_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100, verbose_name='Role'),
        ),
    ]
