# Generated by Django 5.1.3 on 2024-12-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
