# Generated by Django 5.1.3 on 2024-12-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_lesson_is_free_course_is_free'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
    ]
